/* eslint-disable no-unused-vars */
// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Customers = sequelize.define('customers', {
    firstname: {
      type: DataTypes.STRING,
    },
    lastname: {
      type: DataTypes.STRING,
    },
    email: {
      type: DataTypes.STRING,
    },
    phone: {
      type: DataTypes.STRING,
    },
    avatar: {
      type: DataTypes.STRING,
    },
    status: {
      type: DataTypes.STRING,
    },
    rejectReason: {
      type: DataTypes.STRING,
    },
    stripeId: {
      type: DataTypes.STRING,
    },
  }, {
    tableName: 'customers',
    underscored: true,
    timestamps: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Customers.associate = (models) => {
    Customers.hasMany(models.customersSubscriptions, {
      foreignKey: {
        name: 'customerIdKey',
        field: 'customer_id',
      },
      as: 'subscriptions',
    });
    Customers.belongsToMany(models.documents, {
      through: 'customersDocuments',
      as: 'documents',
    });
  };

  return Customers;
};
