// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const ProductsFintech = sequelize.define('productsFintech', {
    label: {
      type: DataTypes.STRING,
    },
    price: {
      type: DataTypes.DECIMAL,
    },
    isRecurrent: {
      type: DataTypes.BOOLEAN,
    },
    isSubscription: {
      type: DataTypes.BOOLEAN,
    },
  }, {
    tableName: 'products_fintech',
    underscored: true,
    timestamps: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  ProductsFintech.addScope('subscriptions', {
    where: {
        isSubscription: true
    }
  });  

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  ProductsFintech.associate = (models) => {
  };

  return ProductsFintech;
};
